name: Deploy

on:
  push:
    tags:
      - 'v*'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: list files
      run: ls -a

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: install req
      run: pip install -r zenodo/req.txt 

    - name: Run script
      run: python zenodo/test.py 
      env:
        VERSION_TAG: ${{ github.event.release.tag_name }}


      

        