ame: Deploy

on:
  push:
    tags:
      - 'v*'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Python script
      run: python your_script.py
      env:
        VERSION_TAG: ${{ github.event.release.tag_name }}

        