name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    tags:
      - 'v*'  
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check code formatting
        run: |
          python -m venv /tmp/venv
          pip install --upgrade pip pre-commit
          pre-commit install
          pre-commit run --all-files

  tag_push_job:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: install req
      run: pip install -r zenodo/req.txt 

    - name: Run script
      run: python zenodo/test.py 
      env:
        VERSION_TAG: ${{ github.ref_name }}